default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: octo_events_jaya_development

test:
  <<: *default
  database: octo_events_jaya_test

production:
  <<: *default
  database: octo_events_jaya_production
